### ISSUE TITLE
setup.py fixes

### ISSUE THREAD

**Issue by jwpeterson** [OpenFAST/python-toolbox#6] opened 2020-11-18 15:29 UTC
Hi,

I didn't see any specific installation instructions for this package, so I tried running
```
pip3 install .
```
from my git clone. This ran into an error:
```
    error: package directory 'pyfast' does not exist
```
which I gathered was caused by the fact that the directory name uses some capital letters, i.e. "pyFAST". So, the patch below seemed to get that working:
```diff
diff --git a/setup.py b/setup.py
index 017b65b..374555b 100644
--- a/setup.py
+++ b/setup.py
@@ -15,11 +15,11 @@ with open(os.path.join(ROOT, "VERSION")) as version_file:
 
 
 setup(
-    name="pyfast",
-    description="pyfast",
+    name="pyFAST",
+    description="pyFAST",
     long_description=LONG_DESCRIPTION,
     version=VERSION,
-    url="https://github.com/RHammond2/pyfast/",
+    url="https://github.com/OpenFAST/python-toolbox",
     author="Rob Hammond",
     author_email="robert.hammond@nrel.gov",
     classifiers=[
@@ -30,7 +30,7 @@ setup(
         "Programming Language :: Python :: 3.7",
         "Topic :: Software Development :: Version Control :: Git",
     ],
-    packages=["pyfast"],
+    packages=["pyFAST"],
     python_requires=">=3.6",
     install_requires=["numpy", "bokeh==1.4.0"],
     extras_require={
```
I then ran into a seemingly related issue when trying to import the new package:
```
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyFAST
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jwpeterson/projects/python-toolbox/pyFAST/__init__.py", line 6, in <module>
    from pyfast import utilities
ModuleNotFoundError: No module named 'pyfast'
```
so it seems that the naming should be updated in a few other places as well? On the other hand, maybe it would be simpler to rename everything to use the lowercase version. I'm definitely not an experienced Python programmer, so please let me know if this is not on the right track.

**Comment by jwpeterson** [comment] 2020-11-18 15:43
> On the other hand, maybe it would be simpler to rename everything to use the lowercase version.

Just a small follow-up, I dropped the diff above and did `git mv pyFAST pyfast` instead. Running `pip3 install .` and `import pyfast` both went smoothly after that.

**Comment by rafmudaf** [comment] 2020-11-18 15:45
Thanks for submitting this issue @jwpeterson. Great to hear you found a solution to your problem. This package is a very crude work-in-progress, at the moment, so I don't expect must of it to work out of the box. Also, use the `dev` branch since that one is a bit ahead of main.

What are you hoping to use this package to do? At the moment, it's a primitive set of tools for driving OpenFAST using system calls, but we have big plans for this in upcoming work.

I think you may be interested to see how I've integrated OpenFAST into a Python script here: https://github.com/rafmudaf/openfast/tree/feature/python_integration/glue-codes/python. For that project, I'm working on establishing a better interface for OpenFAST to C-based driver programs. Most of the infrastructure exists already, but some had to be slightly reworked. In any case, you could do the same thing that the Python code is doing from any driver, like a C++ based software. This will allow you to integrate OpenFAST into a third party software to provide the turbine dynamics.

**Comment by jwpeterson** [comment] 2020-11-18 15:54
> What are you hoping to use this package to do? 

At the moment I'm mainly interested in a Python version of the Matlab/Octave `ReadFASTbinary.m` utility. Since Python is a part of our regular workflow already, it is helpful for to avoid a Matlab/Octave dependency if we can. Currently I'm just interested in reading OpenFAST output files and plotting the results with matplotlib, etc., but it's definitely possible we'll want to have tighter integration like you describe in the future, so thanks for that pointer.

**Comment by rafmudaf** [comment] 2020-11-18 16:04
Ah that's available here: https://github.com/OpenFAST/openfast/tree/master/reg_tests/lib/fast_io.py
Its used in the regression tests scripts, such as https://github.com/OpenFAST/openfast/blob/master/reg_tests/executeOpenfastRegressionCase.py

**Comment by rafmudaf** [comment] 2020-11-18 16:05
Eventually, all of that will be incorporated to this repository (python-toolbox), but for now you're better off using the Python tools in the regression test framework of OpenFAST.

**Comment by ebranlard** [comment] 2020-11-18 16:06
I'd actually recommend using the dev version of the python toolbox.

You'll find different python tools to read FAST files

https://github.com/OpenFAST/python-toolbox/tree/dev

You can look at examples on the readme:
https://github.com/OpenFAST/python-toolbox/tree/dev/pyFAST/input_output

**Comment by jwpeterson** [comment] 2020-11-18 16:18
> Ah that's available here: https://github.com/OpenFAST/openfast/tree/master/reg_tests/lib/fast_io.py

OK, thanks, that's helpful to know. Since we'll be running a "make installed" version of OpenFAST on our production servers, the regression test directories and scripts won't generally be available... So, in my opinion it's quite useful to have something standalone like the python-toolbox which provides some post-processing scripts, etc.

Also, I see that the dev branch already fixed the pyFAST vs. pyfast issue I ran into on master, so thanks to both you and  @ebranlard for that suggestion!

**Comment by ebranlard** [comment] 2020-11-18 16:23
I agree, we should push for the dev branch to be merged into master :)

**Comment by jwpeterson** [comment] 2020-11-18 16:39
Regarding the input_output README.md examples, they need the following fix, again related to the capitalization issue:
```diff
diff --git a/pyFAST/input_output/README.md b/pyFAST/input_output/README.md
index 7ad2c3d..e34b8c0 100644
--- a/pyFAST/input_output/README.md
+++ b/pyFAST/input_output/README.md
@@ -30,7 +30,7 @@ Additional methods may be present depending on the file format.
 
 Read an AeroDyn file, modifies some values and write the modified file:
 ```python
-from pyFast.input_output import FASTInputFile
+from pyFAST.input_output import FASTInputFile
 filename = 'AeroDyn.dat'
 f = FASTInputFile(filename)
 f['TwrAero'] = True
@@ -40,7 +40,7 @@ f.write('AeroDyn_Changed.dat')
 
 Read an OpenFAST binary output file and convert it to a pandas DataFrame
 ```python
-from pyFast.input_output import FASTOutputFile
+from pyFAST.input_output import FASTOutputFile
 df = FASTOutputFile('5MW.outb').toDataFrame()
 time  = df['Time_[s]']
 Omega = df['RotSpeed_[rpm]']
@@ -48,7 +48,7 @@ Omega = df['RotSpeed_[rpm]']
 
 Read a TurbSim binary file
 ```python 
-from pyFast.input_output import TurbSimFile
+from pyFAST.input_output import TurbSimFile
 ts = TurbSimFile('Turb.bts')
 print(ts.keys())
 print(ts['u'].shape)  

```

**Comment by ebranlard** [comment] 2020-11-18 16:47
Thanks for that, I've fixed it now! We'll try to keep things moving, your feedback in the process is much appreciated!

**Comment by jwpeterson** [comment] 2020-11-18 16:59
I have a few other comments. In the process of trying to install the python-toolbox, I once typed:
```
pip3 install pyFAST
```
and that installs the following unrelated package:
```
Metadata-Version: 2.1
Name: pyFAST
Version: 3.1.1.post0
Summary: Python bindings of FAST - a framework for high performance medical image computing and visualization on heterogeneous systems utilizing multi-core CPUs and GPUs.
Home-page: https://github.com/smistad/FAST
Author: Erik Smistad
Author-email: ersmistad@gmail.com
License: BSD 2-clause (package include binary dependencies with other licences, see README)
Platform: UNKNOWN
Classifier: Development Status :: 4 - Beta
Classifier: Operating System :: Microsoft :: Windows
Classifier: Operating System :: POSIX :: Linux
Classifier: Programming Language :: C++
Classifier: Programming Language :: Python :: 3 :: Only
Classifier: Environment :: GPU
Classifier: Topic :: Scientific/Engineering :: Artificial Intelligence
Classifier: Topic :: Scientific/Engineering :: Image Processing
Classifier: Topic :: Scientific/Engineering :: Medical Science Apps.
Classifier: Topic :: Scientific/Engineering :: Visualization
Requires-Python: >=3
Description-Content-Type: text/markdown
Requires-Dist: numpy
```
so it seems that there may be a naming conflict.

Next is something which I suspect is related to my inexperience with Python:

If I run the python3 interpreter from the python-toolbox directory and do `import pyFAST`, it seems to work fine, but if I switch to some other directory and do the same thing, I get the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jwpeterson/.local/lib/python3.6/site-packages/pyFAST/__init__.py", line 12, in <module>
    with open(os.path.join(ROOT, "..", "VERSION")) as version_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jwpeterson/.local/lib/python3.6/site-packages/pyFAST/../VERSION'
```
It appears to be looking for a VERSION file, which is present in the python-toolbox directory but I guess is not installed somehow?

**Comment by jwpeterson** [comment] 2020-11-18 21:23
FYI @ebranlard your commit b2a1a3a2c622ad22bdce42151c1cf325ebd7bfe3 seems to have fixed the error I was seeing with the VERSION file, but now I have run into a different problem. When I try to run my script which has the line
```
from pyFAST.input_output import FASTOutputFile
```
from a directory outside the python-toolbox clone, I get:
```
Traceback (most recent call last):
  File "openfast_reader.py", line 27, in <module>
    from pyFAST.input_output import FASTOutputFile
ModuleNotFoundError: No module named 'pyFAST.input_output'
```
On the other hand, if I do:
```
export PYTHONPATH=/home/jwpeterson/projects/python-toolbox
```
Then I can run the script successfully. I think it should not be necessary to set `PYTHONPATH` explicitly like this, but again I'm not too sure how the Python packaging system is supposed to work... is this something that you can fix as well?

**Comment by ebranlard** [comment] 2020-11-18 21:39
Hey, can you try installing the package like this (when you are the root of the directory:
`python -m pip install -e .`

I've updated the readme accordingly. Keep us in touch! Thanks for testing it!

**Comment by jwpeterson** [comment] 2020-11-18 21:57
Thanks, this seems to have fixed the issue for me, I can now run my script from any directory without setting `PYTHONPATH`

**Closed** 2021-01-01 00:18 UTC
